name: Makefile CI on Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: demo-robot
        
      - name: Checkout PROS CLI
        uses: actions/checkout@v3
        with:
          repository: purduesigbots/pros-cli
          path: pros-cli
        
      - name: Install Dependencies
        run: pip install -e pros-cli
      
      - name: Build Project
        run: make
